mysite/mysite/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^', include('polls.urls')),
    url(r'^polls/', include('polls.urls')),
    url(r'^admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.MEDIA_ROOT)

mysite/polls/urls.py
from django.conf.urls import url

from . import views

app_name = 'polls'

urlpatterns = [
    # ex: /polls/
    url(r'^$', views.index, name='index'),
    # ex: /polls/5/
    url(r'^(?P<question_id>[0-9]+)/$', views.detail, name='detail'),
    # ex: /polls/5/results/
    url(r'^(?P<question_id>[0-9]+)/results/$', views.results, name='results'),
    # ex: /polls/5/vote/
    url(r'^(?P<question_id>[0-9]+)/vote/$', views.vote, name='vote'),

    url(r'^search/', views.search, name='search'),
    url(r'^sort/', views.sort, name='sort'),
    url(r'^basic/', views.BasicView.as_view(), name='basic'),
    # url(r'^questions/', views.QuestionsView.as_view(), name='questions'),
    url(r'^questions/add', views.QuestionsCreateView.as_view(), name='questions'),
    url(r'^questions/(?P<pk>[0-9]+)/$', views.QuestionsUpdateView.as_view(), name='update'),

    url(r'album/add/$', views.AlbumCreate.as_view(), name='album-add'),
    url(r'album/(?P<pk>[0-9]+)/$', views.AlbumUpdate.as_view(), name='album-update'),
]

mysite/polls/models.py
import datetime

from django.db import models
from django.utils import timezone
from django.core.urlresolvers import reverse

class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

    def __str__(self):
        return self.question_text

    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)

class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

class Genres(models.Model):
    GenreOptions = (
        ('ACT', 'action'),
        ('COM', 'comedy'),
    )
    type = models.CharField(max_length=20, choices=GenreOptions)

class Album(models.Model):
    artist = models.CharField(max_length=250)
    genre = models.CharField(max_length=250)
    image = models.FileField()

    def get_absolute_url(self):
        return reverse('polls:index')

GenderOptions = (
    ('male', 'male'),
    ('female', 'female'),
    ('other', 'other'),
)
BACKGROUND = (
        ('Sephardi', 'sephardi'),
        ('Ashkenazi', 'ashkenazi'),
)
BACKGROUND2 = (
        ('1', 'sephardi'),
        ('2', 'ashkenazi'),
        ('3', 'mizrachi'),
        ('4', 'other'),
)

class Background(models.Model):
    background = models.CharField(max_length=10)

    def __str__(self):
        return self.background

class Gender(models.Model):
    gender = models.CharField(max_length=20)

    def __str__(self):
        return self.gender

class Questions(models.Model):
    first_name = models.CharField(max_length=250)
    last_name = models.CharField(max_length=250)
    gender = models.ForeignKey(Gender)
    background = models.ManyToManyField(Background)

mysite/polls/forms.py
from django import forms

from .models import Questions, Background, Gender

from django.core.exceptions import ValidationError
from django.utils.translation import ugettext_lazy as _
import datetime  # for checking renewal date range.

# This gives value then name
SortOptions = (
    ('LAB', 'labor'),
    ('CAR', 'cars'),
    ('TRU', 'trucks'),
    ('WRI', 'writing'),
)

class SortForm(forms.Form):
    sort_choice = forms.ChoiceField(widget=forms.Select(attrs={'onchange': 'this.form.submit();'}), choices=SortOptions)

class BasicForm(forms.Form):
    name = forms.CharField(max_length=20, label='First Name')
    sort_choice = forms.MultipleChoiceField(choices=SortOptions)


class QuestionsForm(forms.ModelForm):
    gender = forms.ModelChoiceField(queryset=Gender.objects, empty_label=None, widget=forms.RadioSelect)

    class Meta:
        model = Questions
        exclude = ['']
        widgets = {
            'gender': forms.RadioSelect(),
            'background': forms.CheckboxSelectMultiple(),
        }

class BackgroundForm(forms.ModelForm):
    class Meta:
        model = Background
        exclude = ['']

mysite/polls/views.py
from django.http import HttpResponseRedirect, HttpResponse
from django.shortcuts import get_object_or_404, render
from django.http import Http404
from django.core.urlresolvers import reverse
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.core.urlresolvers import reverse_lazy
from django.views import View

import datetime

from .forms import SortForm, BasicForm, QuestionsForm

from .models import Question, Album, Questions

# ----Original----
# def index(request):
#     return HttpResponse("Hello, world. You're at the polls index.")

# ----Changed to----
# def index(request):
#     latest_question_list = Question.objects.order_by('-pub_date')[:5]
#     output = ', '.join([q.question_text for q in latest_question_list])
#     return HttpResponse(output)

# ----Changed again to----
# from django.template import loader
# def index(request):
    # latest_question_list = Question.objects.order_by('-pub_date')[:5]
    # template = loader.get_template('polls/index.html')
    # context = {
    #     'latest_question_list': latest_question_list,
    # }
    # return HttpResponse(template.render(context, request))

# ----Which is equivalent to----
# returns an HttpResponse object of the given template rendered with the given context.
def index(request):
    latest_question_list = Question.objects.order_by('-pub_date')[:5]
    context = {
        'latest_question_list': latest_question_list,
        'sort_form': SortForm,
    }
    return render(request, 'polls/index.html', context)
# ----Originally----
# def detail(request, question_id):
#     return HttpResponse("You're looking at question %s." % question_id)

# ----Changed to----
# def detail(request, question_id):
#     try:
#         question = Question.objects.get(pk=question_id)
#     except Question.DoesNotExist:
#         raise Http404("Question does not exist")
#     return render(request, 'polls/detail.html', {'question': question})

#----Equivalently---
def detail(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'polls/detail.html', {'question': question})


# def vote(request, question_id):
#     return HttpResponse("You're voting on question %s." % question_id)

# ----Updated to----
from .models import Choice, Question
# ...
def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        return render(request, 'polls/detail.html', {
            'question': question,
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))

# ----Originally----
# def results(request, question_id):
#     response = "You're looking at the results of question %s."
#     return HttpResponse(response % question_id)

#----Updated to----
def results(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'polls/results.html', {'question': question})

#----From https://developer.mozilla.org/en-US/docs/Learn/Server-side/Django/Forms----
def renew_book_librarian(request, pk):
    book_inst=get_object_or_404(BookInstance, pk = pk)

    # If this is a POST request then process the Form data
    if request.method == 'POST':

        # Create a form instance and populate it with data from the request (binding):
        form = RenewBookForm(request.POST)

        # Check if the form is valid:
        if form.is_valid():
            # process the data in form.cleaned_data as required (here we just write it to the model due_back field)
            book_inst.due_back = form.cleaned_data['renewal_date']
            book_inst.save()

            # redirect to a new URL:
            return HttpResponseRedirect(reverse('all-borrowed') )

    # If this is a GET (or any other method) create the default form.
    else:
        proposed_renewal_date = datetime.date.today() + datetime.timedelta(weeks=3)
        form = RenewBookForm(initial={'renewal_date': proposed_renewal_date,})

    return render(request, 'catalog/book_renew_librarian.html', {'form': form, 'bookinst':book_inst})

def search(request):
    """ Handle registration form """
    if request.method == 'POST':
        response = dict(
            errors=list(),
        )

        search_result = request.POST['search']

        context = {}
        context['results'] = search_result
        return render(request, 'polls/selected.html', context)
    else:
        return render(request, 'polls/selected.html')


def sort(request):
    """ Handle registration form """
    if request.method == 'POST':
        response = dict(
            errors=list(),
        )

        sort_option = request.POST['sort_choice']

        context = {}
        context['results'] = sort_option
        return render(request, 'polls/selected.html', context)
    else:
        return render(request, 'polls/selected.html')

class AlbumCreate(CreateView):
    model = Album
    fields = ['artist', 'genre', 'image']

class AlbumUpdate(UpdateView):
    model = Album
    fields = ['artist', 'genre']

class AlbumDelete(DeleteView):
    model = Album
    success_url = reverse_lazy('polls:index')

class BasicView(View):
    def get(self, request, *args, **kwargs):
        context = {
            "form": BasicForm
        }
        return render(request, "polls/basic.html", context) # Try Django 1.8 & 1.9 http://joincfe.com/youtube

    def post(self, request, *args, **kwargs):
        form = BasicForm(request.POST)
        if form.is_valid():
            print(form.cleaned_data)

        context = {
            "form": form
        }
        return render(request, "polls/basic.html", context)

# class QuestionsView(View):
#     def get(self, request, *args, **kwargs):
#         context = {
#             "form": QuestionsForm
#         }
#         return render(request, "polls/questions.html", context)
#
#     def post(self, request, *args, **kwargs):
#         form = QuestionsForm(request.POST)
#         if form.is_valid():
#             print(form.cleaned_data)
#
#         context = {
#             "form": form
#         }
#         return render(request, "polls/questions.html", context)

class QuestionsCreateView(CreateView):
    form_class = QuestionsForm
    template_name = "polls/questions.html"
    success_url = '../../'

# class QuestionsUpdateView(UpdateView):
#     model = Questions
#     fields = '__all__'
#     template_name = "polls/questions.html"

class QuestionsUpdateView(UpdateView):
    model = Questions
    form_class = QuestionsForm
    template_name = "polls/questions.html"
    success_url = '../../'

mysite/polls/templates/polls/album_form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Album</title>
</head>
<body>
    <h1>Album</h1>

    <form action="{% url 'polls:album-add' %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="form-group">

{#        {% include 'polls/form-template.html' %}#}
{# In polls/form-template.html write the following#}
{#            {% for field in form %}#}
{#                    <label>{{ form.genre.label_tag }}</label>#}
{#                    <div>{{ form.genre }}</div>#}
{##}
{#                    <label>{{ form.artist.label_tag }}</label>#}
{#                    <div>{{ form.artist }}</div>#}
{#            {% endfor %}#}

            {{ form.as_p }}
            <button type="submit">Submit</button>
        </div>
    </form>

{#    {% for album in all_albums %}#}
{#        <img src="{{ album.album_logo.url }}">#}
{#    {% endfor %}#}

</body>
</html>

mysite/polls/templates/polls/basic.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Basic</title>
</head>
<body>
    <h1>Basic Form</h1>
    <form action='.' method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Submit">
    </form>
</body>
</html>

mysite/polls/templates/polls/book_renew_librarian.html
{% block content %}

    <h1>Renew: {{bookinst.book.title}}</h1>
    <p>Borrower: {{bookinst.borrower}}</p>
    <p{% if bookinst.is_overdue %} class="text-danger"{% endif %}>Due date: {{bookinst.due_back}}</p>

    <form action="" method="post">
        {% csrf_token %}
        <table>
        {{ form }}
        </table>
        <input type="submit" value="Submit" />
    </form>

{% endblock %}

mysite/polls/templates/polls/detail.html
<h1>{{ question.question_text }}</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'polls:vote' question.id %}" method="post">
{% csrf_token %}
{% for choice in question.choice_set.all %}
    <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}" />
    <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br />
{% endfor %}
<input type="submit" value="Vote" />
</form>

mysite/polls/templates/polls/index.html
{% if latest_question_list %}
    <ul>
    {% for question in latest_question_list %}
{#    ----Originally----#}
{#        <li><a href="/polls/{{ question.id }}/">{{ question.question_text }}</a></li>#}
{#    ----Updated to----#}
{#        now this link points to the url named 'detail' in polls/urls.py instead of the hardcoded polls/ #}
        <li><a href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}

<h1>Search</h1>

<section class="search-section">
    <form method="POST" action='{% url 'polls:search' %}'>
        {% csrf_token %}
        <input type="text" class="search-bar" name="search">
        <input type="submit" value="Search">
    </form>
</section>

{% block content %}
<h1>Choice</h1>
<form role="form" action="{% url 'polls:sort' %}" method="post">
    {% csrf_token %}
    {{ sort_form.as_p }}
</form>
{% endblock %}

<h1>Go to CreateView</h1>
<a href="{% url 'polls:album-add' %}">Add an album</a>

mysite/polls/templates/polls/name.html
<h1>Hello</h1>

<form action="/your-name/" method="post">
    {% csrf_token %}
    {{ form }}
    <input type="submit" value="Submit" />
</form>

mysite/polls/templates/polls/questions.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Questions</title>
</head>
<body>
    <h1>Questions</h1>
    <form action='' method="post">
        {% csrf_token %}

        {{ form.first_name.label_tag }}
        {{ form.first_name }}
        {{ form.last_name.label_tag }}
        {{ form.last_name }}

        <br>
        {{ form.gender.label_tag }}
        <br>
        {% for choice in form.gender %}
             <span class="radio">{{ choice.tag }}</span>{{ choice.choice_label }}
            {% cycle '' '<br>' %}
        {% endfor %}

        <br>

        {{ form.background.label_tag }}
        {{ form.background }}


{#     <li>#}
{#        <label for="id_background_0">#}
{#            <input id="id_background_0" name="background" type="checkbox" value="1">Sephardi#}
{#        </label>#}
{#    </li>#}
{#    <li>#}
{#        <label for="id_background_1">#}
{#            <input id="id_background_1" name="background" type="checkbox" value="2">Ashkenazi#}
{#        </label>#}
{#    </li>#}

        <input type="submit" value="Submit">
    </form>
</body>
</html>

mysite/polls/templates/polls/results.html
<h1>{{ question.question_text }}</h1>

<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'polls:detail' question.id %}">Vote again?</a>

mysite/polls/templates/polls/selected.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Selected</title>
</head>
<body>
You have searched:
{{results}}
</body>
</html>