mysite-generic-views/mysite/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^polls/', include('polls.urls')),
    url(r'^admin/', admin.site.urls),
]

mysite-generic-views/polls/urls.py
from django.conf.urls import url

from . import views

app_name = 'polls'

urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),
    url(r'^(?P<pk>[0-9]+)/results/$', views.ResultsView.as_view(), name='results'),
    url(r'^(?P<question_id>[0-9]+)/vote/$', views.vote, name='vote'),
    url(r'^postad/', views.PostAdPage.as_view())
]

mysite-generic-views/polls/models.py
import datetime

from django.db import models
from django.utils import timezone

# Create your models here.
class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

    def __str__(self):
        return self.question_text

    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)

class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

CATEGORIES = (
    ('LAB', 'labor'),
    ('CAR', 'cars'),
    ('TRU', 'trucks'),
    ('WRI', 'writing'),
)
LOCATIONS = (
    ('BRO', 'Bronx'),
    ('BRK', 'Brooklyn'),
    ('QNS', 'Queens'),
    ('MAN', 'Manhattan'),
    ('STN', 'Staten Island'),
)

class PostAd(models.Model):
    name        = models.CharField(max_length=50)
    email       = models.EmailField()
    gist        = models.CharField(max_length=50)
    category    = models.CharField(max_length=3, choices=CATEGORIES)
    location    = models.CharField(max_length=3, choices=LOCATIONS)
    description = models.TextField(max_length=300)
    expire      = models.DateField()

mysite-generic-views/polls/forms.py
from django import forms
from .models import PostAd

CATEGORIES = (
    ('LAB', 'labor'),
    ('CAR', 'cars'),
    ('TRU', 'trucks'),
    ('WRI', 'writing'),
)
LOCATIONS = (
    ('BRO', 'Bronx'),
    ('BRK', 'Brooklyn'),
    ('QNS', 'Queens'),
    ('MAN', 'Manhattan'),
)

class PostAdForm(forms.ModelForm):
    error_css_class = 'error'

    category = forms.ChoiceField(choices=CATEGORIES, required=True )
    location = forms.ChoiceField(choices=LOCATIONS, required=True )

    class Meta:
        model = PostAd

        widgets = {
            'name': forms.TextInput(attrs={'placeholder': 'What\'s your name?'}),
            'email': forms.TextInput(attrs={'placeholder': 'john@example.com'}),
            'gist': forms.TextInput(attrs={'placeholder': 'In a few words, I\'m looking for/to...'}),
            'expire': forms.TextInput(attrs={'placeholder': 'MM/DD/YYYY'})
        }

mysite-generic-views/polls/views.py
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.views import generic

from django.http import HttpResponse
from django.views.generic import FormView
from .models import PostAd
from .forms import PostAdForm

from .models import Choice, Question

class IndexView(generic.ListView):
    template_name = 'polls/index.html'
    context_object_name = 'latest_question_list'

    def get_queryset(self):
        """Return the last five published questions."""
        return Question.objects.order_by('-pub_date')[:5]


class DetailView(generic.DetailView):
    model = Question
    template_name = 'polls/detail.html'


class ResultsView(generic.DetailView):
    model = Question
    template_name = 'polls/results.html'


# def vote(request, question_id):
#     return HttpResponse("You're voting on question %s." % question_id)

# ----Updated to----
from .models import Choice, Question
# ...
def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        return render(request, 'polls/detail.html', {
            'question': question,
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))

class PostAdPage(FormView):
    template_name = 'post_ad.html'
    success_url = '/awesome/'
    form_class = PostAdForm

    def form_valid(self, form):
        return HttpResponse("Sweeeeeet.")

mysite-generic-views/polls/templates/polls/detail.html
<h1>{{ question.question_text }}</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'polls:vote' question.id %}" method="post">
{% csrf_token %}
{% for choice in question.choice_set.all %}
    <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}" />
    <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br />
{% endfor %}
<input type="submit" value="Vote" />
</form>

mysite-generic-views/polls/templates/polls/index.html
{% if latest_question_list %}
    <ul>
    {% for question in latest_question_list %}
{#    ----Originally----#}
{#        <li><a href="/polls/{{ question.id }}/">{{ question.question_text }}</a></li>#}
{#    ----Updated to----#}
{#        now this link points to the url named 'detail' in polls/urls.py instead of the hardcoded polls/ #}
        <li><a href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}

mysite-generic-views/polls/templates/polls/post_ad.html
{% comment %}

This is the display for the 'Post Ad' form.

URL: postad/
Model: PostAd
ModelForm: PostAdForm
View: PostAdPage [FormView]
View Return: HttpResponse : message - "Sweeeeeeeet."

* = preset when user is logged in.

{% endcomment %}

{% block content %}
<form action="/postad/" method="post">{% csrf_token %}
    <!-- *name -->
    {{  form.non_field_errors }}
    <div class="fieldWrapper">
        {{ form.name.errors }}
        <label for="id_name">Name</label>
        {{ form.name }}
    </div>
    <!-- *email -->
    <div class="fieldWrapper">
        {{ form.email.errors }}
        <label for="id_email">Email</label>
        {{ form.email }}
    </div>
    <!-- gist -->
    <div class="fieldWrapper">
        {{ form.gist.errors }}
        <label for="id_gist">Gist</label>
        {{ form.gist }}
    </div>
    <!-- category -->
    <div class="fieldWrapper">
        {{ form.category.errors }}
        <label for="id_category">Category</label>
        {{ form.category }}
    </div>
    <!-- location -->
    <div class="fieldWrapper">
        {{ form.location.errors }}
        <label for="id_name">Location</label>
        {{ form.location }}
    </div>
    <!-- description -->
    <div class="fieldWrapper">
        {{ form.description.errors }}
        <label for="id_description">Description</label>
        {{ form.description }}
    </div>
    <!-- expire -->
    <div class="fieldWrapper">
        {{ form.expire.errors }}
        <label for="id_expire">Expire</label>
        {{ form.expire }}
    </div>
    <button type="submit">
        <i class="fa fa-thumb-tack"></i> Post
    </button>
</form>
{% endblock %}

mysite-generic-views/polls/templates/polls/results.html
<h1>{{ question.question_text }}</h1>

<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'polls:detail' question.id %}">Vote again?</a>